### ISSUE TITLE
Command execution failed

### ISSUE THREAD

**Issue by Jacq3lin3** [Romualdi-Lab/brewerix-cli#1]
Hello, 

I dowloaded  BrewerIX and provided an RNA-seq fastq sample however I got the following error message: 
``` command execution failed``` 

What could this be to? 
Thanks a lot for your help

Jackie

**Comment by cavei** [comment]
Hi,
could you please send me the log file?
You should have a file named workflow-***.log (* are numbers) in the working directory with the fastq files. Could you send the latest created, please.
Thank you.

**Comment by Jacq3lin3** [comment]
[workflow-200608154447.log](https://github.com/Romualdi-Lab/brewerix-cli/files/4752050/workflow-200608154447.log)

Here you go, thanks a lot.

**Comment by cavei** [comment]
According to our tests, we run into a pysam/htslib error reported also here https://github.com/pysam-developers/pysam/pull/870.
We menage to solve it with the newer version of brewerIX 0.40.2

Thanks again for your report

**Comment by Jacq3lin3** [comment]
Hello, 
I have tried to reinstall brewerIX and I have the current version 0.40.2.
However I still run into the same error. 

Any suggestions? 
Here is the the new log 
[workflow-200615144753.log](https://github.com/Romualdi-Lab/brewerix-cli/files/4781148/workflow-200615144753.log)


Thanks a lot
Jackie

**Comment by cavei** [comment]
Hi,
according to the log the installation run smooth this time.
The problem is "invalid filename for paired-end reads: ES2e_34803_AGTCAA_read2.fastq.gz"
BrewerIX is able to recognize paired end files from the directory but paired files must have suffix _1.
You should rename you samples in the form: ES2e_34803_AGTCAA_2.fastq.gz
I will specify it on the user manual, Thanks a lot!

**Comment by Jacq3lin3** [comment]
Ah that 's a pity, it would be great if this could be fixed.

Often times it is impossible to rename sequencing files and copying them (to  renaming them) is a lot of extra storage.
Any alternatives?

Thanks

**Comment by cavei** [comment]
Unfortunately it is really difficult to handle all the possible names. We used the nomenclature "_1" and "_2" as it is used also by fastq-dump (sra toolkit).

I would suggest you to not duplicate the files but to create symbolic links with new names in a new directory  (https://www.howtogeek.com/297721/how-to-create-and-use-symbolic-links-aka-symlinks-on-a-mac/)

Hope this help!

**Comment by Jacq3lin3** [comment]
Hello, 
I tryed your suggestion. I created a link with  ```ln-s```  in the directory from which I run BrewerIX .
Then I changed the name of those linked files to ES1a_34791_ATCACG_1.fastq.gz and ES1a_34791_ATCACG_2.fastq.gz 

However the jobs stops right away: 



Here is the log
```Darwin C02WW3J6HV2Q.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
[Tue, 30 Jun 2020 11:15:29 UTC] Alignment
Workflow guess LOI version: 0.9.0
error: file not found: ES1a_34791_ATCACG_1.fastq.gz
```

**Comment by Jacq3lin3** [comment]
and if I would restore the original names(that you mentioned should be in a different format), it also stops at the very beginning with the following log: 
```
Darwin C02WW3J6HV2Q.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
Workflow guess LOI version: 0.9.0
invalid filename for paired-end reads: ES1a_34791_ATCACG_read1.fastq.gz
```

Any suggestions? 
Brewer IX version is 0.40.2

Thanks  lot!

**Comment by cavei** [comment]
Hi,
sorry for the delay in my answer.

According to your report in the first case it seams that your symbolic link do not link an actual file
"error: file not found: ES1a_34791_ATCACG_1.fastq.gz"
in fact you get an error file not found.
Be sure that you are not linking remote files that you can not access in your computer.

In the second example you've got an "invalid file name" error because BrewerIX is able to recognize as paired-end only files with suffix _1.fastq.gz and _2.fastq.gz. As I told you in a previous post, we can not predict all the possible paired names and we use the convention of SRA toolkit.

If you have further issues do not hesitate to write.
